# Generated by Django 4.2.16 on 2024-10-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrafanaOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grafaid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrafanaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grafaid', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrafanaUserManag.grafanaorganization')),
            ],
        ),
    ]
