# Generated by Django 4.2.16 on 2024-10-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrafanaUserManag', '0002_user_delete_grafanauser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
