# Generated by Django 4.2.16 on 2024-10-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GrafanaUserManag', '0003_rename_username_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GrafanaUserManag.grafanaorganization'),
        ),
    ]
